version: '3.8'

services:
  app:
    # build:
    #   context: .  # Path to the app's Dockerfile
    #   dockerfile: Dockerfile  # Ensures it uses the provided Dockerfile
    image: diogofi/osrsapp:latest
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    working_dir: /usr/src/app  # Sets the working directory inside the container
    command: python ./main.py  # Runs the app

  mongodb:
    image: mongodb/mongodb-community-server:4.4.0-ubuntu2004
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Persistent data storage

  mongo-backup:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - /usr/backups:/backup  # Mount host directory for backups
      depends_on:
        - mongodb
volumes:
  mongo-data:
