name: Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set env
      run: echo "CURRENT_DATE=$(date +%s)" >> $GITHUB_ENV
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      
    - uses: docker/setup-qemu-action@v2
      with:
          platforms: 'arm64,arm'
          
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build --platform=linux/arm64/v8 . --file Dockerfile -t diogofi/osrsapp:latest
        
    - name: Push the Docker image
      run: docker push diogofi/osrsapp:latest
